FROM openjdk:17

COPY . /coap
WORKDIR coap

RUN ./mvnw clean assembly:assembly -DskipTests -f server/pom.xml

RUN ls /coap/server/target
ENTRYPOINT ["java","-jar","/coap/server/target/server-1.0-SNAPSHOT-jar-with-dependencies.jar"]
