version: '3'

services:
    coap-server:
        image: chpanag/coap-server:latest
        build:
            context: .
            dockerfile: Dockerfile.server
        ports:
            - 5683:5683/udp

